import { state, EVENT_DATE, ADMIN_KEY, roleById, peopleFor, totalSlots, missing, scoringStations, scoreKey, scoreFor, totalFor, rankedParticipants } from "./state.js";
import { esc, slug, toast, downloadCSV } from "./utils.js";
import { db, collection, addDoc, deleteDoc, doc, setDoc, serverTimestamp } from "./firebase.js";

export function shell(content) {
  return `<div class="shell"><header class="topbar"><div class="brand"><button class="menu" onclick="go('home')">☰</button><div><h1>RVN Event Manager</h1><p>${esc(state.currentEventName)} · O-Ritt & Turnier</p></div></div><img class="logo" src="assets/logo.png" alt="RVN Logo"></header><main class="main">${content}</main><nav class="bottom">${nav("home","🏠","Home")}${nav("oritt","🐴","O-Ritt")}${nav("turnier","🏇","Turnier")}${nav("helfer","👥","Helfer")}${nav("admin","👑","Admin")}</nav></div>`;
}
const nav = (id, icon, label) => `<button class="nav ${state.page === id ? "active" : ""}" onclick="go('${id}')"><span>${icon}</span>${label}</button>`;

function countdown() {
  const diff = Math.max(0, EVENT_DATE - new Date());
  const d = Math.floor(diff / 86400000), h = Math.floor(diff / 3600000) % 24, m = Math.floor(diff / 60000) % 60, s = Math.floor(diff / 1000) % 60;
  return `<div class="countdown"><div class="countbox"><strong>${d}</strong><span>Tage</span></div><div class="countbox"><strong>${h}</strong><span>Std</span></div><div class="countbox"><strong>${m}</strong><span>Min</span></div><div class="countbox"><strong>${s}</strong><span>Sek</span></div></div>`;
}

export function pageView() {
  if (state.page === "home") return homePage();
  if (state.page === "oritt") return orittPage();
  if (state.page === "turnier") return turnierPage();
  if (state.page === "helfer") return helperPage();
  if (state.page === "infos") return infoPage();
  if (state.page === "pdf") return pdfPage();
  if (state.page === "news") return newsPage();
  if (state.page === "ergebnisse") return resultsPage();
  if (state.page === "meldestelle") return meldestellePage();
  if (state.page === "archiv") return archivePage();
  if (state.page === "admin") return adminPage();
  if (state.page.startsWith("role:")) return rolePage(state.page.split(":")[1]);
  return homePage();
}

function homePage() {
  return `<section class="hero"><div><div class="kicker">Reit- und Fahrverein Neuendettelsau e.V.</div><h2>RVN Event<br>Manager</h2><p>O-Ritt & Turnier – alles an einem Ort</p></div></section><section class="grid two"><article class="card"><div class="icon">🐴</div><h3>O-Ritt 2026</h3><p>${esc(state.settings.eventTitle)} – Helfer, Meldestelle, Ergebnisse und Adminbereich.</p><button class="arrow" onclick="go('oritt')">›</button></article><article class="card"><div class="icon">🏇</div><h3>Turnier</h3><p>Bereich ist vorbereitet. Helfer und Turnierfunktionen können später ergänzt werden.</p><button class="arrow" onclick="go('turnier')">›</button></article></section>`;
}

function orittPage() {
  return `<section class="hero"><div><div class="kicker">Orientierungsritt 2026</div><h2>${esc(state.settings.eventTitle)}</h2><p>${esc(state.settings.eventSubtitle)}</p><div class="chip">📅 25. Juli 2026</div>${countdown()}</div></section><section class="grid"><article class="card"><div class="icon">📋</div><h3>Meldestelle</h3><p>Teilnehmer, Startnummern und Status verwalten.</p><button class="arrow" onclick="go('meldestelle')">›</button></article><article class="card"><div class="icon">👥</div><h3>Als Helfer eintragen</h3><p>Trag dich live in einen freien Bereich ein.</p><button class="arrow" onclick="go('helfer')">›</button></article><article class="card"><div class="icon">🏆</div><h3>Ergebnisse</h3><p>Punkte pro Station und Rangliste.</p><button class="arrow" onclick="go('ergebnisse')">›</button></article><article class="card"><div class="icon">📢</div><h3>Aktuelles</h3><p>Kurze Hinweise für alle.</p><button class="arrow" onclick="go('news')">›</button></article></section><section class="panel"><div class="head"><div><h2>👥 Helferübersicht</h2><p class="sub">Live-Stand – <span class="accent">${state.helpers.length} von ${totalSlots()}</span> Helferplätzen belegt</p></div><button class="btn" onclick="go('helfer')">Zur Detailansicht ›</button></div>${helperOverview(false)}</section>`;
}

function turnierPage(){return `<section class="panel"><h2>🏇 Turnier</h2><div class="notice">Der Turnierbereich ist vorbereitet. Keine Konkurrenz zur Homepage, nur Organisation.</div><div class="cards"><div class="info"><h3>👥 Helfer</h3><p>Vorbereitet.</p></div><div class="info"><h3>📋 Meldestelle</h3><p>Vorbereitet.</p></div><div class="info"><h3>🏆 Ergebnisse</h3><p>Vorbereitet.</p></div></div></section>`}
function helperOverview(detailed=true){return `<div class="list">${state.roles.map(r=>{const c=peopleFor(r.id).length,f=Math.max(0,Number(r.max)-c),cls=f===0?"full":f<=1?"low":"free";return `<div class="row"><div class="r-icon">${r.icon}</div><div><strong>${esc(r.name)}</strong>${detailed?`<div class="sub">${c} / ${r.max} eingetragen</div>${r.description?`<div class="sub">${esc(r.description)}</div>`:""}`:""}</div><div class="bar"><div style="width:${Math.min(100,c/Number(r.max)*100)}%"></div></div><div>${c} / ${r.max}</div><div class="status ${cls}">${f===0?"Voll":f+" frei"}</div><button class="menu" onclick="openRole('${r.id}')">›</button></div>`}).join("")}</div>`}
export const helperPage=()=>`<section class="panel"><div class="head"><div><h2>👥 O-Ritt Helfer eintragen</h2><p class="sub">Die Liste aktualisiert sich live.</p></div><button class="btn alt" onclick="shareWhatsApp()">📲 WhatsApp teilen</button></div>${helperForm()}</section><section class="panel"><h2>Helferübersicht</h2>${helperOverview(true)}</section>`;
function helperForm(pref=state.roles[0]?.id||""){return `<form id="helperForm" class="form"><label>Name<input id="name" required placeholder="Dein Name"></label><label>Telefon<input id="phone" required placeholder="Telefonnummer"></label><label>Bereich<select id="role">${state.roles.map(r=>`<option value="${r.id}" ${pref===r.id?"selected":""}>${r.icon} ${esc(r.name)}</option>`).join("")}</select></label><label>Zeitraum<select id="time"><option>ganztags</option><option>vormittags</option><option>nachmittags</option><option>abends</option><option>nach Absprache</option></select></label><label class="full">Bemerkung<textarea id="note" placeholder="z. B. mit Auto, ab 15 Uhr"></textarea></label><button class="btn full" type="submit">Eintragen</button></form>`}
function rolePage(id){const r=roleById(id); if(!r)return `<section class="panel"><h2>Bereich nicht gefunden</h2></section>`; const p=peopleFor(id),f=Math.max(0,Number(r.max)-p.length);return `<section class="panel"><button class="btn light" onclick="go('helfer')">‹ Zurück</button><h2>${r.icon} ${esc(r.name)}</h2><p class="sub"><span class="accent">${p.length} / ${r.max}</span> Helfer eingetragen · ${f===0?"voll":f+" frei"}</p>${r.description?`<p class="sub">${esc(r.description)}</p>`:""}<div class="bar" style="margin:16px 0"><div style="width:${Math.min(100,p.length/Number(r.max)*100)}%"></div></div><h3>Eingetragene Helfer</h3>${p.length?p.map(entryHtml).join(""):`<p class="sub">Noch niemand eingetragen.</p>`}</section><section class="panel"><h2>Ich möchte hier helfen</h2>${f>0?helperForm(id):`<p>Dieser Bereich ist bereits voll.</p>`}</section>`}
function entryHtml(h){return `<div class="entry"><div><strong>${esc(h.name)}</strong><br><small>${esc(h.time||"")} · ${esc(h.note||"Keine Bemerkung")}</small>${state.isAdmin?`<br><small>Tel: ${esc(h.phone||"")}</small>`:""}</div>${state.isAdmin?`<button class="btn danger" onclick="deleteHelper('${h.id}')">Löschen</button>`:""}</div>`}
const infoPage=()=>`<section class="panel"><h2>ℹ️ Infos zum O-Ritt</h2><div class="cards"><div class="info"><h3>📅 Datum</h3><p>Samstag, 25.07.2026</p></div><div class="info"><h3>🏖️ Motto</h3><p>Beach Please – wir reiten! Sommer, Sonne, Sattel.</p></div><div class="info"><h3>🗺️ Strecken</h3><p>Kleine Runde ca. 7 km, große Runde ca. 17 km.</p></div></div></section>`;
const pdfPage=()=>`<section class="panel"><h2>📄 PDF-Anmeldung 2026</h2><div class="notice">Teilnehmeranmeldung läuft weiterhin über die offiziellen PDF-Unterlagen.</div></section>`;
function newsPage(){return `<section class="panel"><h2>📢 Aktuelles</h2>${state.news.length?state.news.map(n=>`<div class="entry"><div><strong>${esc(n.title)}</strong><p>${esc(n.text)}</p></div>${state.isAdmin?`<button class="btn danger" onclick="deleteNews('${n.id}')">Löschen</button>`:""}</div>`).join(""):`<p class="sub">Noch keine aktuellen Hinweise.</p>`}</section>`}
function statusLabel(s){return s==="started"?"Gestartet":s==="finished"?"Im Ziel":s==="withdrawn"?"Zurückgezogen":"Gemeldet"}
function participantForm(){return `<form id="participantForm" class="form"><label>Startnummer<input id="participantStart" placeholder="z. B. 12"></label><label>Name / Reiterpaar<input id="participantName" required placeholder="z. B. Lisa & Anna"></label><label>Pferd<input id="participantHorse" placeholder="Pferdename"></label><label>Startzeit<input id="participantStartTime" type="time"></label><label>Strecke<select id="participantRoute"><option>Kleine Runde 7 km</option><option>Große Runde 17 km</option></select></label><button class="btn full" type="submit">Teilnehmer hinzufügen</button></form>`}
function meldestellePage(){const sorted=[...state.participants].sort((a,b)=>String(a.startTime||"99:99").localeCompare(String(b.startTime||"99:99")) || Number(a.startNumber||9999)-Number(b.startNumber||9999));return `<section class="panel"><div class="head"><div><h2>📋 Meldestelle</h2><p class="sub">Teilnehmer, Startnummern, Pferde und Status.</p></div>${state.isAdmin?`<button class="btn alt" onclick="exportParticipantsCSV()">Teilnehmer CSV</button>`:""}</div>${state.isAdmin?participantForm():`<div class="notice">Nur Admin.</div>`}<h3>Teilnehmerliste</h3>${sorted.length?sorted.map(p=>`<div class="entry"><div><strong>${esc(p.startNumber||"-")} · ${esc(p.name)}</strong><br><small>Startzeit: ${esc(p.startTime||"-")} · Pferd: ${esc(p.horse||"-")} · Strecke: ${esc(p.route||"-")} · Status: ${statusLabel(p.status)}</small></div>${state.isAdmin?`<div><input type="time" id="starttime-${p.id}" value="${esc(p.startTime||"")}" style="max-width:130px"><button class="btn light" onclick="setParticipantStartTime('${p.id}')">Zeit speichern</button><button class="btn light" onclick="setParticipantStatus('${p.id}','registered')">Gemeldet</button><button class="btn light" onclick="setParticipantStatus('${p.id}','started')">Gestartet</button><button class="btn light" onclick="setParticipantStatus('${p.id}','finished')">Im Ziel</button><button class="btn danger" onclick="deleteParticipant('${p.id}')">Löschen</button></div>`:""}</div>`).join(""):`<p class="sub">Noch keine Teilnehmer.</p>`}</section>`}
function resultsPage(){const ranking=rankedParticipants();return `<section class="panel"><div class="head"><div><h2>🏆 Ergebnisse</h2><p class="sub">Punkte pro Station und Rangliste.</p></div>${state.isAdmin?`<button class="btn alt" onclick="exportResultsCSV()">Ergebnisse CSV</button>`:""}</div>${state.isAdmin?scoreEntryPanel():""}<h3>Rangliste</h3>${ranking.length?ranking.map((p,i)=>`<div class="entry"><div><strong>${i+1}. ${esc(p.name)}</strong><br><small>Start-Nr.: ${esc(p.startNumber||"-")} · Pferd: ${esc(p.horse||"-")} · Strecke: ${esc(p.route||"-")}</small></div><strong>${totalFor(p.id)} Punkte</strong></div>`).join(""):`<p class="sub">Noch keine Teilnehmer.</p>`}</section>`}
function scoreEntryPanel(){return `<div class="entries">${state.participants.map(p=>`<details class="entry"><summary><strong>${esc(p.startNumber||"")} ${esc(p.name)}</strong> · Gesamt: ${totalFor(p.id)} Punkte</summary><form class="form score-form" data-participant="${p.id}" style="margin-top:12px">${scoringStations().map(st=>`<label>${st.icon} ${esc(st.name)} ${st.maxPoints ? `(max. ${st.maxPoints})` : ""}<input name="${st.id}" type="number" min="0" max="${st.maxPoints ?? 999}" step="0.5" value="${scoreFor(p.id,st.id)?.points??""}" placeholder="Punkte"></label>`).join("")}<button class="btn full" type="submit">Punkte speichern</button></form></details>`).join("")||`<p class="sub">Noch keine Teilnehmer.</p>`}</div>`}
function archivePage(){return `<section class="panel"><h2>📁 Veranstaltungsarchiv</h2><div class="notice">Vorbereitet für O-Ritt und Turnier je Jahr. Keine Homepage-Funktionen.</div><div class="cards"><div class="info"><h3>🐴 O-Ritt 2026</h3><p>Aktiv</p></div><div class="info"><h3>🏇 Turnier 2026</h3><p>Vorbereitet</p></div></div></section>`}
function adminPage(){if(!state.isAdmin)return `<section class="panel"><h2>🔒 Admin-Login</h2><form id="adminLoginForm" class="form"><label class="full">Admin-Passwort<input id="adminLoginPassword" type="password"></label><button class="btn full">Einloggen</button></form></section>`;return `<section class="panel"><div class="head"><div><h2>👑 Admin Dashboard</h2><p class="sub">Du bist als Admin angemeldet.</p></div><button class="btn light" onclick="adminLogout()">Abmelden</button></div><div class="stats"><div class="stat"><strong>${state.helpers.length}</strong><span>Helfer</span></div><div class="stat"><strong>${totalSlots()}</strong><span>Plätze</span></div><div class="stat"><strong>${missing()}</strong><span>frei</span></div><div class="stat"><strong>${state.participants.length}</strong><span>Teilnehmer</span></div></div><button class="btn" onclick="exportCSV()">Helfer CSV</button><button class="btn alt" onclick="go('ergebnisse')">Ergebnisse</button><button class="btn light" onclick="go('meldestelle')">Meldestelle</button><button class="btn light" onclick="go('archiv')">Archiv</button>${helperOverview(true)}</section>${adminSettings()}`}
function adminSettings(){return `<section class="panel"><h2>⚙️ Einstellungen</h2><form id="settingsForm" class="form"><label>Event-Titel<input id="setTitle" value="${esc(state.settings.eventTitle)}"></label><label>Untertitel<input id="setSubtitle" value="${esc(state.settings.eventSubtitle)}"></label><label class="full">WhatsApp-Text<textarea id="setWhatsapp">${esc(state.settings.whatsappText)}</textarea></label><label>Neues Admin-Passwort<input id="setPassword" placeholder="Leer lassen = unverändert"></label><button class="btn full">Einstellungen speichern</button></form></section><section class="panel"><h2>📢 News schreiben</h2><form id="newsForm" class="form"><label>Titel<input id="newsTitle"></label><label class="full">Text<textarea id="newsText"></textarea></label><button class="btn full">News veröffentlichen</button></form></section><section class="panel"><h2>🧩 Stationen und Bereiche verwalten</h2><form id="roleForm" class="form"><label>Reihenfolge<input id="roleOrder" type="number" value="99"></label><label>Name<input id="roleName"></label><label>Emoji<input id="roleIcon"></label><label>Plätze<input id="roleMax" type="number" min="1" value="4"></label><label>Max. Punkte<input id="roleMaxPoints" type="number" min="0" value="10"></label><label class="full">Beschreibung<textarea id="roleDescription"></textarea></label><button class="btn full">Bereich hinzufügen</button></form>${state.roles.map(r=>`<form class="entry role-edit" data-role="${r.id}"><div style="display:grid;gap:8px;width:100%"><strong>${r.icon} ${esc(r.name)}</strong><input name="order" type="number" value="${r.order??999}"><input name="name" value="${esc(r.name)}"><input name="icon" value="${esc(r.icon)}"><input name="max" type="number" min="1" value="${r.max}"><input name="maxPoints" type="number" min="0" value="${r.maxPoints ?? 10}" placeholder="Max. Punkte"><textarea name="description">${esc(r.description||"")}</textarea></div><div><button class="btn light" type="button" onclick="moveRole('${r.id}',-1)">↑</button><button class="btn light" type="button" onclick="moveRole('${r.id}',1)">↓</button><button class="btn alt">Speichern</button><button class="btn danger" type="button" onclick="deleteRole('${r.id}')">Entfernen</button></div></form>`).join("")}</section>`}

export function attachForms(render){
  const helper=document.getElementById("helperForm"); if(helper)helper.addEventListener("submit",submitHelper);
  const login=document.getElementById("adminLoginForm"); if(login)login.addEventListener("submit",e=>{e.preventDefault(); if(document.getElementById("adminLoginPassword").value===state.settings.adminPassword){state.isAdmin=true;localStorage.setItem(ADMIN_KEY,"yes");toast("Admin angemeldet.");render()}else toast("Falsches Passwort.")});
  const sf=document.getElementById("settingsForm"); if(sf)sf.addEventListener("submit",saveSettings);
  const nf=document.getElementById("newsForm"); if(nf)nf.addEventListener("submit",submitNews);
  const rf=document.getElementById("roleForm"); if(rf)rf.addEventListener("submit",addRole);
  const pf=document.getElementById("participantForm"); if(pf)pf.addEventListener("submit",addParticipant);
  document.querySelectorAll(".role-edit").forEach(f=>f.addEventListener("submit",saveRole));
  document.querySelectorAll(".score-form").forEach(f=>f.addEventListener("submit",saveScores));
}
async function submitHelper(e){e.preventDefault();const role=document.getElementById("role").value,r=roleById(role);if(peopleFor(role).length>=Number(r.max))return toast("Dieser Bereich ist bereits voll.");const payload={name:document.getElementById("name").value.trim(),phone:document.getElementById("phone").value.trim(),role,time:document.getElementById("time").value,note:document.getElementById("note").value.trim(),createdAt:serverTimestamp()};if(!payload.name||!payload.phone)return toast("Bitte Name und Telefon eintragen.");await addDoc(collection(db,"helpers"),payload);toast("Danke! Du bist eingetragen.");e.target.reset()}
async function saveSettings(e){e.preventDefault();const next={...state.settings,eventTitle:document.getElementById("setTitle").value.trim(),eventSubtitle:document.getElementById("setSubtitle").value.trim(),whatsappText:document.getElementById("setWhatsapp").value.trim()};const pw=document.getElementById("setPassword").value.trim();if(pw)next.adminPassword=pw;await setDoc(doc(db,"settings","main"),next,{merge:true});toast("Einstellungen gespeichert.")}
async function submitNews(e){e.preventDefault();const title=document.getElementById("newsTitle").value.trim(),text=document.getElementById("newsText").value.trim();if(!title||!text)return toast("Bitte Titel und Text eintragen.");await addDoc(collection(db,"news"),{title,text,createdAt:serverTimestamp()});e.target.reset();toast("News veröffentlicht.")}
async function addRole(e){e.preventDefault();const name=document.getElementById("roleName").value.trim();if(!name)return toast("Bitte Namen eintragen.");await setDoc(doc(db,"roles",slug(name)),{order:Number(document.getElementById("roleOrder").value||99),name,icon:document.getElementById("roleIcon").value.trim()||"👥",max:Number(document.getElementById("roleMax").value||1),maxPoints:Number(document.getElementById("roleMaxPoints").value||0),description:document.getElementById("roleDescription").value.trim(),createdAt:serverTimestamp()});e.target.reset();toast("Bereich hinzugefügt.")}
async function saveRole(e){e.preventDefault();const id=e.currentTarget.dataset.role;await setDoc(doc(db,"roles",id),{order:Number(e.currentTarget.order.value||999),name:e.currentTarget.name.value.trim(),icon:e.currentTarget.icon.value.trim()||"👥",max:Number(e.currentTarget.max.value||1),maxPoints:Number(e.currentTarget.maxPoints?.value||0),description:e.currentTarget.description.value.trim()},{merge:true});toast("Bereich gespeichert.")}
async function addParticipant(e){e.preventDefault();const payload={startNumber:document.getElementById("participantStart").value.trim(),name:document.getElementById("participantName").value.trim(),horse:document.getElementById("participantHorse").value.trim(),startTime:document.getElementById("participantStartTime").value,route:document.getElementById("participantRoute").value,status:"registered",createdAt:serverTimestamp()};if(!payload.name)return toast("Bitte Teilnehmernamen eintragen.");await addDoc(collection(db,"participants"),payload);e.target.reset();toast("Teilnehmer hinzugefügt.")}
async function saveScores(e){e.preventDefault();const participantId=e.currentTarget.dataset.participant;for(const st of scoringStations()){const raw=e.currentTarget[st.id]?.value;if(raw!==undefined&&raw!=="")await setDoc(doc(db,"scores",scoreKey(participantId,st.id)),{participantId,stationId:st.id,points:Number(raw),updatedAt:serverTimestamp()},{merge:true})}toast("Punkte gespeichert.")}
window.openRole=id=>{state.page="role:"+id;window.renderApp();scrollTo({top:0,behavior:"smooth"})}
window.adminLogout=()=>{state.isAdmin=false;localStorage.removeItem(ADMIN_KEY);toast("Admin abgemeldet.");window.renderApp()}
window.deleteHelper=async id=>{if(!state.isAdmin)return toast("Bitte Admin einloggen.");if(confirm("Eintrag löschen?"))await deleteDoc(doc(db,"helpers",id))}
window.deleteNews=async id=>{if(state.isAdmin&&confirm("News löschen?"))await deleteDoc(doc(db,"news",id))}
window.deleteRole=async id=>{if(!state.isAdmin)return;if(peopleFor(id).length)return toast("Bereich hat noch Helfer.");if(confirm("Bereich entfernen?"))await deleteDoc(doc(db,"roles",id))}
window.deleteParticipant=async id=>{if(state.isAdmin&&confirm("Teilnehmer löschen?"))await deleteDoc(doc(db,"participants",id))}
window.setParticipantStartTime=async(id)=>{if(!state.isAdmin)return toast("Bitte Admin einloggen.");const el=document.getElementById("starttime-"+id);await setDoc(doc(db,"participants",id),{startTime:el?.value||"",updatedAt:serverTimestamp()},{merge:true});toast("Startzeit gespeichert.")};
window.setParticipantStatus=async(id,status)=>{if(!state.isAdmin)return toast("Bitte Admin einloggen.");await setDoc(doc(db,"participants",id),{status,updatedAt:serverTimestamp()},{merge:true});toast("Teilnehmerstatus gespeichert.")}
window.exportCSV=()=>{const rows=[["Bereich","Name","Telefon","Zeitraum","Bemerkung"]];state.helpers.forEach(h=>rows.push([roleById(h.role)?.name||h.role,h.name,h.phone,h.time||"",h.note||""]));downloadCSV(rows,"RVN_Oritt_Helferliste.csv")}
window.exportParticipantsCSV=()=>{const rows=[["Startnummer","Startzeit","Teilnehmer","Pferd","Strecke","Status"]];[...state.participants].sort((a,b)=>String(a.startTime||"99:99").localeCompare(String(b.startTime||"99:99")) || Number(a.startNumber||9999)-Number(b.startNumber||9999)).forEach(p=>rows.push([p.startNumber||"",p.startTime||"",p.name||"",p.horse||"",p.route||"",p.status||"registered"]));downloadCSV(rows,"RVN_Oritt_Teilnehmer.csv")}
window.exportResultsCSV=()=>{const rows=[["Rang","Startnummer","Startzeit","Teilnehmer","Pferd","Strecke",...scoringStations().map(s=>s.name),"Gesamt"]];rankedParticipants().forEach((p,i)=>rows.push([i+1,p.startNumber||"",p.startTime||"",p.name||"",p.horse||"",p.route||"",...scoringStations().map(st=>scoreFor(p.id,st.id)?.points||0),totalFor(p.id)]));downloadCSV(rows,"RVN_Oritt_Ergebnisse.csv")}
window.moveRole=async(id,delta)=>{if(!state.isAdmin)return toast("Bitte Admin einloggen.");const r=state.roles.find(x=>x.id===id);if(!r)return;await setDoc(doc(db,"roles",id),{order:Number(r.order??999)+delta},{merge:true});toast("Reihenfolge geändert.")};
window.shareWhatsApp=async()=>{const text=state.settings.whatsappText;if(navigator.share)await navigator.share({title:"RVN Event Manager",text,url:location.href});else window.open(`https://wa.me/?text=${encodeURIComponent(text+" "+location.href)}`,"_blank")}
