import { firebaseConfig } from "./firebase-config.js";
import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getFirestore, collection, addDoc, deleteDoc, doc, setDoc, getDoc, serverTimestamp, onSnapshot, query, orderBy } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js";

const EVENT_DATE = new Date("2026-07-25T09:00:00");
const ADMIN_KEY = "rvn_admin_logged_in";
const defaultSettings = {adminPassword:"RVN2026!",whatsappText:"🐴 RVN Event Manager – Helferanmeldung O-Ritt 2026: Trag dich hier ein:",eventTitle:"Beach Please – wir reiten!",eventSubtitle:"Sommer, Sonne, Sattel"};
const defaultRoles = [...Array.from({length:9},(_,i)=>({id:`station-${i+1}`,name:`Station ${i+1}`,icon:"🐴",max:5,description:""})),{id:"haengerplatz",name:"Hängerplatz",icon:"🚗",max:4,description:"Einweisung und Ordnung am Hängerparkplatz."},{id:"grillen",name:"Grillteam",icon:"🔥",max:6,description:"Unterstützung beim Grillen und Abspülen am Abend."},{id:"meldestelle",name:"Meldestelle",icon:"📋",max:4,description:"Anmeldung, Startunterlagen und Rückfragen."},{id:"aufbau",name:"Aufbauteam",icon:"🔧",max:6,description:"Aufbau vor der Veranstaltung."},{id:"abbau",name:"Abbauteam",icon:"🔨",max:6,description:"Abbau nach der Veranstaltung."},{id:"springer-kfz",name:"Springer mit KFZ",icon:"🚙",max:4,description:"Kontrolle der Stationen mit Fahrzeug."}];
let helpers=[],news=[],settings={...defaultSettings},roles=[...defaultRoles],db=null,page="home",isAdmin=localStorage.getItem(ADMIN_KEY)==="yes";
const appEl=document.getElementById("app");
const logo=()=>'<img class="header-logo" src="rvn-logo-original.jpg" alt="RVN Logo">';
const esc=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const slug=s=>String(s).toLowerCase().replace(/ä/g,"ae").replace(/ö/g,"oe").replace(/ü/g,"ue").replace(/ß/g,"ss").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")+"-"+Date.now().toString().slice(-5);
const roleById=id=>roles.find(r=>r.id===id);
const peopleFor=id=>helpers.filter(h=>h.role===id);
const totalSlots=()=>roles.reduce((a,r)=>a+Number(r.max||0),0);
const missing=()=>Math.max(0,totalSlots()-helpers.length);

function shell(c){return `<div class="app-shell"><header class="topbar"><div class="brand"><button class="menu-btn" onclick="go('home')">☰</button><div><h1>RVN Event Manager</h1><p>O-Ritt & Turnier</p></div></div>${logo()}</header><main class="main">${c}</main><nav class="bottom-nav">${nav("home","🏠","Home")}${nav("oritt","🐴","O-Ritt")}${nav("turnier","🏇","Turnier")}${nav("helfer","👥","Helfer")}${nav("admin","👑","Admin")}</nav></div>`}
function nav(id,i,l){return `<button class="nav-item ${page===id?"active":""}" onclick="go('${id}')"><span>${i}</span>${l}</button>`}
window.go=id=>{page=id;render();scrollTo({top:0,behavior:"smooth"})};

function countdown(){const diff=Math.max(0,EVENT_DATE-new Date()),d=Math.floor(diff/86400000),h=Math.floor(diff/3600000)%24,m=Math.floor(diff/60000)%60,s=Math.floor(diff/1000)%60;return `<div class="countdown"><div class="countbox"><strong>${d}</strong><span>Tage</span></div><div class="countbox"><strong>${h}</strong><span>Std</span></div><div class="countbox"><strong>${m}</strong><span>Min</span></div><div class="countbox"><strong>${s}</strong><span>Sek</span></div></div>`}
function homePage(){return `<section class="hero"><div class="hero-title"><div class="kicker">Reit- und Fahrverein Neuendettelsau e.V.</div><h2>RVN Event<br>Manager</h2><p>O-Ritt & Turnier – alles an einem Ort</p></div></section><section class="grid-actions two-actions"><article class="action-card"><div class="icon">🐴</div><h3>O-Ritt 2026</h3><p>${esc(settings.eventTitle)} – Helfer, Infos, PDFs und Adminbereich.</p><button class="arrow" onclick="go('oritt')">›</button></article><article class="action-card"><div class="icon">🏇</div><h3>Turnier</h3><p>Bereich ist vorbereitet. Helfer und Turnierfunktionen können später ergänzt werden.</p><button class="arrow" onclick="go('turnier')">›</button></article></section>`}
function orittPage(){return `<section class="hero"><div class="hero-title"><div class="kicker">Orientierungsritt 2026</div><h2>${esc(settings.eventTitle)}</h2><p>${esc(settings.eventSubtitle)}</p><div class="date-chip">📅 25. Juli 2026</div>${countdown()}</div></section><section class="grid-actions"><article class="action-card"><div class="icon">📄</div><h3>PDF-Anmeldung</h3><p>Teilnehmeranmeldung läuft 2026 über PDF-Unterlagen.</p><button class="arrow" onclick="go('pdf')">›</button></article><article class="action-card"><div class="icon">👥</div><h3>Als Helfer eintragen</h3><p>Trag dich live in einen freien Bereich ein.</p><button class="arrow" onclick="go('helfer')">›</button></article><article class="action-card"><div class="icon">📍</div><h3>Infos</h3><p>Strecken, Siegerehrung und Teilnahmehinweise.</p><button class="arrow" onclick="go('infos')">›</button></article><article class="action-card"><div class="icon">📢</div><h3>Aktuelles</h3><p>Kurze Hinweise für alle.</p><button class="arrow" onclick="go('news')">›</button></article></section><section class="panel"><div class="panel-head"><div><h2>👥 Helferübersicht</h2><p class="sub">Live-Stand – <span class="accent">${helpers.length} von ${totalSlots()}</span> Helferplätzen belegt</p></div><button class="btn" onclick="go('helfer')">Zur Detailansicht ›</button></div>${helperOverview(false)}</section>`}
function turnierPage(){return `<section class="panel"><h2>🏇 Turnier</h2><div class="notice">Der Turnierbereich ist vorbereitet. Hier können später Helfer, Zeiteinteilung, Meldestelle und Ergebnisse ergänzt werden.</div><div class="cards"><div class="info-card"><h3>👥 Helfer</h3><p>Vorbereitet für Turnier-Helferplanung.</p></div><div class="info-card"><h3>📋 Meldestelle</h3><p>Platzhalter für Turnierorganisation.</p></div><div class="info-card"><h3>🏆 Ergebnisse</h3><p>Kann später ergänzt werden.</p></div></div></section>`}
function helperOverview(d=true){return `<div class="helper-list">${roles.map(r=>{const c=peopleFor(r.id).length,f=Math.max(0,Number(r.max)-c),cls=f===0?"full":f<=1?"low":"free";return `<div class="helper-row"><div class="row-icon">${r.icon}</div><div><strong>${esc(r.name)}</strong>${d?`<div class="sub">${c} / ${r.max} eingetragen</div>`:""}</div><div class="bar"><div style="width:${Math.min(100,c/Number(r.max)*100)}%"></div></div><div>${c} / ${r.max}</div><div class="status ${cls}">${f===0?"Voll":f+" frei"}</div><button class="menu-btn" onclick="openRole('${r.id}')">›</button></div>`}).join("")}</div>`}
window.openRole=id=>{page="role:"+id;render();scrollTo({top:0,behavior:"smooth"})};
function helperPage(){return `<section class="panel"><div class="panel-head"><div><h2>👥 O-Ritt Helfer eintragen</h2><p class="sub">Die Liste aktualisiert sich live.</p></div><button class="btn secondary" onclick="shareWhatsApp()">📲 WhatsApp teilen</button></div>${helperForm()}</section><section class="panel"><h2>Helferübersicht</h2>${helperOverview(true)}</section>`}
function helperForm(pref=roles[0]?.id||""){return `<form id="helperForm" class="form-grid"><label>Name<input id="name" required placeholder="Dein Name"></label><label>Telefon<input id="phone" required placeholder="Telefonnummer"></label><label>Bereich<select id="role">${roles.map(r=>`<option value="${r.id}" ${pref===r.id?"selected":""}>${r.icon} ${esc(r.name)}</option>`).join("")}</select></label><label>Zeitraum<select id="time"><option>ganztags</option><option>vormittags</option><option>nachmittags</option><option>abends</option><option>nach Absprache</option></select></label><label class="fullspan">Bemerkung<textarea id="note" placeholder="z. B. mit Auto, ab 15 Uhr"></textarea></label><button class="btn fullspan" type="submit">Eintragen</button></form>`}
function rolePage(id){const r=roleById(id);if(!r)return `<section class="panel"><h2>Bereich nicht gefunden</h2></section>`;const p=peopleFor(id),f=Math.max(0,Number(r.max)-p.length);return `<section class="panel"><button class="btn light" onclick="go('helfer')">‹ Zurück</button><div class="panel-head" style="margin-top:14px"><div><h2>${r.icon} ${esc(r.name)}</h2><p class="sub"><span class="accent">${p.length} / ${r.max}</span> Helfer eingetragen · ${f===0?"voll":f+" frei"}</p>${r.description?`<p class="sub">${esc(r.description)}</p>`:""}</div></div><div class="bar" style="margin:16px 0"><div style="width:${Math.min(100,p.length/Number(r.max)*100)}%"></div></div><h3>Eingetragene Helfer</h3><div class="entries">${p.length?p.map(entryHtml).join(""):`<p class="sub">Noch niemand eingetragen.</p>`}</div><h3>Noch freie Plätze</h3><div class="cards">${Array.from({length:f},()=>`<div class="info-card"><h3>➕ Platz frei</h3><p>Hier wird noch Hilfe gesucht.</p></div>`).join("")||`<div class="info-card"><h3>✅ Voll</h3><p>Dieser Bereich ist besetzt.</p></div>`}</div></section><section class="panel"><h2>Ich möchte hier helfen</h2>${f>0?helperForm(id):`<p>Dieser Bereich ist bereits voll.</p>`}</section>`}
function entryHtml(h){return `<div class="entry"><div><strong>${esc(h.name)}</strong><br><small>${esc(h.time||"")} · ${esc(h.note||"Keine Bemerkung")}</small>${isAdmin?`<br><small>Tel: ${esc(h.phone||"")}</small>`:""}</div>${isAdmin?`<button class="btn danger" onclick="deleteHelper('${h.id}')">Löschen</button>`:""}</div>`}
function infoPage(){return `<section class="panel"><h2>ℹ️ Infos zum O-Ritt</h2><div class="cards"><div class="info-card"><h3>📅 Datum</h3><p>Samstag, 25.07.2026</p></div><div class="info-card"><h3>🏖️ Motto</h3><p>Beach Please – wir reiten! Sommer, Sonne, Sattel.</p></div><div class="info-card"><h3>🗺️ Strecken</h3><p>Kleine Runde ca. 7 km, große Runde ca. 17 km.</p></div><div class="info-card"><h3>🏆 Siegerehrung</h3><p>Im Reitverein Neuendettelsau.</p></div><div class="info-card"><h3>🎭 Kostümwertung</h3><p>Das ausgefallenste Kostüm bekommt einen Sonderpreis.</p></div><div class="info-card"><h3>🚴 Begleiter</h3><p>Mit geländetauglichem Fahrrad und Grundkondition möglich.</p></div><div class="info-card"><h3>⛑️ Teilnahme</h3><p>Helmpflicht, Teilnahme auf eigene Gefahr, Minderjährige nur mit Erwachsenen.</p></div><div class="info-card"><h3>⏰ Anmeldefrist</h3><p>10.07.2026</p></div></div></section>`}
function pdfPage(){return `<section class="panel"><h2>📄 PDF-Anmeldung 2026</h2><div class="notice">Die Teilnehmeranmeldung für den O-Ritt 2026 läuft weiterhin über die offiziellen PDF-Unterlagen. Eine Online-Anmeldung kann 2027 ergänzt werden.</div><div class="cards"><div class="info-card"><h3>📝 Anmeldung</h3><p>PDF-Anmeldeformular wie gewohnt einreichen.</p></div><div class="info-card"><h3>✅ Teilnahmebedingungen</h3><p>Haftung, Versicherung, Helmpflicht und Minderjährige werden über die Anmeldung bestätigt.</p></div><div class="info-card"><h3>📬 Rückgabe</h3><p>Bitte die Kontaktmöglichkeit aus der Ausschreibung nutzen.</p></div></div></section>`}
function newsPage(){return `<section class="panel"><h2>📢 Aktuelles</h2><div class="news-list">${news.length?news.map(n=>`<div class="news-item"><strong>${esc(n.title)}</strong><p>${esc(n.text)}</p><div class="small">${n.createdAt?.toDate?n.createdAt.toDate().toLocaleString("de-DE"):""}</div>${isAdmin?`<button class="btn danger" onclick="deleteNews('${n.id}')">Löschen</button>`:""}</div>`).join(""):`<p class="sub">Noch keine aktuellen Hinweise.</p>`}</div></section>`}
function adminLogin(){return `<section class="panel"><h2>🔒 Admin-Login</h2><p class="sub">Passwort eingeben, um Export, Löschen und Einstellungen zu nutzen.</p><form id="adminLoginForm" class="form-grid"><label class="fullspan">Admin-Passwort<input id="adminLoginPassword" type="password" placeholder="Passwort"></label><button class="btn fullspan" type="submit">Einloggen</button></form></section>`}
function adminPage(){if(!isAdmin)return adminLogin();const full=roles.filter(r=>peopleFor(r.id).length>=Number(r.max)).length;return `<section class="panel"><div class="panel-head"><div><h2>👑 Admin Dashboard</h2><p class="sub">Du bist als Admin angemeldet.</p></div><button class="btn light" onclick="adminLogout()">Abmelden</button></div><div class="admin-grid"><div class="stat"><strong>${helpers.length}</strong><span>Helfer</span></div><div class="stat"><strong>${totalSlots()}</strong><span>Plätze</span></div><div class="stat"><strong>${missing()}</strong><span>frei</span></div><div class="stat"><strong>${full}</strong><span>voll</span></div></div><div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:14px"><button class="btn" onclick="exportCSV()">CSV exportieren</button><button class="btn secondary" onclick="shareWhatsApp()">WhatsApp-Link teilen</button><button class="btn light" onclick="print()">Druckliste öffnen</button></div>${helperOverview(true)}</section>${adminSettings()}`}
function adminSettings(){return `<section class="panel"><h2>⚙️ Einstellungen</h2><form id="settingsForm" class="form-grid"><label>Event-Titel<input id="setTitle" value="${esc(settings.eventTitle)}"></label><label>Untertitel<input id="setSubtitle" value="${esc(settings.eventSubtitle)}"></label><label class="fullspan">WhatsApp-Text<textarea id="setWhatsapp">${esc(settings.whatsappText)}</textarea></label><label>Neues Admin-Passwort<input id="setPassword" placeholder="Leer lassen = unverändert"></label><button class="btn fullspan" type="submit">Einstellungen speichern</button></form></section><section class="panel"><h2>📢 News schreiben</h2><form id="newsForm" class="form-grid"><label>Titel<input id="newsTitle" placeholder="z. B. Hängerparkplatz öffnet um 7:30 Uhr"></label><label class="fullspan">Text<textarea id="newsText" placeholder="Kurzer Hinweis"></textarea></label><button class="btn fullspan" type="submit">News veröffentlichen</button></form></section><section class="panel"><h2>🧩 Stationen und Bereiche verwalten</h2><div class="notice">Hier kannst du Stationen umbenennen, Beschreibungen ergänzen und Helferzahlen ändern.</div><form id="roleForm" class="form-grid"><label>Name<input id="roleName" placeholder="z. B. Fototeam"></label><label>Emoji<input id="roleIcon" placeholder="📸"></label><label>Plätze<input id="roleMax" type="number" min="1" value="4"></label><label class="fullspan">Beschreibung<textarea id="roleDescription" placeholder="Kurze Beschreibung der Aufgabe"></textarea></label><button class="btn fullspan" type="submit">Bereich hinzufügen</button></form><div class="entries">${roles.map(r=>`<form class="entry role-edit" data-role="${r.id}"><div style="display:grid;gap:8px;width:100%"><strong>${r.icon} ${esc(r.name)}</strong><input name="name" value="${esc(r.name)}"><input name="icon" value="${esc(r.icon)}"><input name="max" type="number" min="1" value="${r.max}"><textarea name="description" placeholder="Beschreibung">${esc(r.description||"")}</textarea></div><div style="display:grid;gap:8px"><button class="btn secondary" type="submit">Speichern</button><button class="btn danger" type="button" onclick="deleteRole('${r.id}')">Entfernen</button></div></form>`).join("")}</div></section>`}
function render(){let c="";if(page==="home")c=homePage();else if(page==="oritt")c=orittPage();else if(page==="turnier")c=turnierPage();else if(page==="helfer")c=helperPage();else if(page==="infos")c=infoPage();else if(page==="pdf")c=pdfPage();else if(page==="news")c=newsPage();else if(page==="admin")c=adminPage();else if(page.startsWith("role:"))c=rolePage(page.split(":")[1]);appEl.innerHTML=shell(c);attachForms()}
function attachForms(){let f=document.getElementById("helperForm");if(f)f.addEventListener("submit",submitHelper);let l=document.getElementById("adminLoginForm");if(l)l.addEventListener("submit",e=>{e.preventDefault();let pw=document.getElementById("adminLoginPassword").value;if(pw===settings.adminPassword){isAdmin=true;localStorage.setItem(ADMIN_KEY,"yes");toast("Admin angemeldet.");render()}else toast("Falsches Passwort.")});let sf=document.getElementById("settingsForm");if(sf)sf.addEventListener("submit",saveSettings);let nf=document.getElementById("newsForm");if(nf)nf.addEventListener("submit",submitNews);let rf=document.getElementById("roleForm");if(rf)rf.addEventListener("submit",addRole);document.querySelectorAll(".role-edit").forEach(form=>form.addEventListener("submit",saveRole))}
async function submitHelper(e){e.preventDefault();let role=document.getElementById("role").value,r=roleById(role),count=peopleFor(role).length;if(count>=Number(r.max)){toast("Dieser Bereich ist bereits voll.");return}let payload={name:document.getElementById("name").value.trim(),phone:document.getElementById("phone").value.trim(),role,time:document.getElementById("time").value,note:document.getElementById("note").value.trim(),createdAt:serverTimestamp()};if(!payload.name||!payload.phone){toast("Bitte Name und Telefon eintragen.");return}await addDoc(collection(db,"helpers"),payload);toast("Danke! Du bist eingetragen.");e.target.reset()}
async function saveSettings(e){e.preventDefault();let next={...settings,eventTitle:document.getElementById("setTitle").value.trim(),eventSubtitle:document.getElementById("setSubtitle").value.trim(),whatsappText:document.getElementById("setWhatsapp").value.trim()};let pw=document.getElementById("setPassword").value.trim();if(pw)next.adminPassword=pw;await setDoc(doc(db,"settings","main"),next,{merge:true});toast("Einstellungen gespeichert.")}
async function submitNews(e){e.preventDefault();let title=document.getElementById("newsTitle").value.trim(),text=document.getElementById("newsText").value.trim();if(!title||!text){toast("Bitte Titel und Text eintragen.");return}await addDoc(collection(db,"news"),{title,text,createdAt:serverTimestamp()});e.target.reset();toast("News veröffentlicht.")}
async function addRole(e){e.preventDefault();let name=document.getElementById("roleName").value.trim(),icon=document.getElementById("roleIcon").value.trim()||"👥",max=Number(document.getElementById("roleMax").value||1),description=document.getElementById("roleDescription").value.trim();if(!name){toast("Bitte Namen eintragen.");return}await setDoc(doc(db,"roles",slug(name)),{name,icon,max,description,createdAt:serverTimestamp()});e.target.reset();toast("Bereich hinzugefügt.")}
async function saveRole(e){e.preventDefault();let id=e.currentTarget.dataset.role;let data={name:e.currentTarget.name.value.trim(),icon:e.currentTarget.icon.value.trim()||"👥",max:Number(e.currentTarget.max.value||1),description:e.currentTarget.description.value.trim(),createdAt:serverTimestamp()};await setDoc(doc(db,"roles",id),data,{merge:true});toast("Bereich gespeichert.")
window.deleteHelper=async id=>{if(!isAdmin){toast("Bitte Admin einloggen.");return}if(confirm("Eintrag löschen?"))await deleteDoc(doc(db,"helpers",id))};
window.deleteNews=async id=>{if(!isAdmin)return;if(confirm("News löschen?"))await deleteDoc(doc(db,"news",id))};
window.deleteRole=async id=>{if(!isAdmin)return;if(peopleFor(id).length){toast("Bereich hat noch Helfer.");return}if(confirm("Bereich entfernen?"))await deleteDoc(doc(db,"roles",id))};
window.adminLogout=()=>{isAdmin=false;localStorage.removeItem(ADMIN_KEY);toast("Admin abgemeldet.");render()};
window.exportCSV=()=>{if(!isAdmin){toast("Bitte Admin einloggen.");return}let rows=[["Bereich","Name","Telefon","Zeitraum","Bemerkung"]];helpers.forEach(h=>rows.push([roleById(h.role)?.name||h.role,h.name,h.phone,h.time||"",h.note||""]));let csv=rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\\n");let blob=new Blob([csv],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="RVN_Oritt_Helferliste.csv";a.click();URL.revokeObjectURL(url)};
window.shareWhatsApp=async()=>{let text=settings.whatsappText;if(navigator.share)await navigator.share({title:"RVN Event Manager",text,url:location.href});else window.open(`https://wa.me/?text=${encodeURIComponent(text+" "+location.href)}`,"_blank")};
window.toast=msg=>{let el=document.createElement("div");el.className="toast";el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2600)};
async function ensureDefaults(){let s=await getDoc(doc(db,"settings","main"));if(!s.exists())await setDoc(doc(db,"settings","main"),defaultSettings);let seeded=await getDoc(doc(db,"meta","rolesSeeded"));if(!seeded.exists()){for(const r of defaultRoles){await setDoc(doc(db,"roles",r.id),{...r,createdAt:serverTimestamp()},{merge:true})}await setDoc(doc(db,"meta","rolesSeeded"),{done:true,createdAt:serverTimestamp()})}}
function init(){try{let app=initializeApp(firebaseConfig);db=getFirestore(app);ensureDefaults();onSnapshot(doc(db,"settings","main"),s=>{if(s.exists())settings={...defaultSettings,...s.data()};render()});onSnapshot(query(collection(db,"roles"),orderBy("createdAt","asc")),snap=>{let custom=snap.docs.map(d=>({id:d.id,...d.data()}));roles=custom.length?custom:defaultRoles;render()});onSnapshot(query(collection(db,"helpers"),orderBy("createdAt","asc")),snap=>{helpers=snap.docs.map(d=>({id:d.id,...d.data()}));render()});onSnapshot(query(collection(db,"news"),orderBy("createdAt","desc")),snap=>{news=snap.docs.map(d=>({id:d.id,...d.data()}));render()})}catch(e){console.error(e);render();toast("Firebase-Konfiguration prüfen.")}setInterval(()=>{if(page==="oritt")render()},1000)}
init();
